import {
  MapPin,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Search,
  Menu,
  User,
  ShoppingBag,
  ShoppingBasket,
  Clock,
  Star,
  Bike,
  Plus,
  Minus,
  ArrowLeft,
  ArrowRight,
  HeartPulse,
  HeartHandshake,
  Heart,
  Sparkles,
  Utensils,
  UtensilsCrossed,
  Store,
  Pill,
  Flower,
  BadgePercent,
  Building2,
  Phone,
  Tag,
  Receipt,
  X,
} from 'lucide-react'

const REGISTRY = {
  'map-pin': MapPin,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  search: Search,
  menu: Menu,
  user: User,
  'shopping-bag': ShoppingBag,
  'shopping-basket': ShoppingBasket,
  clock: Clock,
  star: Star,
  bike: Bike,
  plus: Plus,
  minus: Minus,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'heart-pulse': HeartPulse,
  'heart-handshake': HeartHandshake,
  heart: Heart,
  sparkles: Sparkles,
  utensils: Utensils,
  'utensils-crossed': UtensilsCrossed,
  store: Store,
  pill: Pill,
  flower: Flower,
  'badge-percent': BadgePercent,
  'building-2': Building2,
  phone: Phone,
  tag: Tag,
  receipt: Receipt,
  x: X,
}

export default function Icon({ name, size = 18, className = '', strokeWidth = 2 }) {
  const Cmp = REGISTRY[name]
  if (!Cmp) return null
  return <Cmp size={size} strokeWidth={strokeWidth} className={className} aria-hidden="true" />
}
